# Generated by ANTLR 4.8
from antlr4 import *
from io import StringIO
from typing.io import TextIO
import sys


def serializedATN():
    with StringIO() as buf:
        buf.write("\3\u608b\ua72a\u8133\ub9ed\u417c\u3be7\u7786\u5964\2 ")
        buf.write("\u00cf\b\1\4\2\t\2\4\3\t\3\4\4\t\4\4\5\t\5\4\6\t\6\4\7")
        buf.write("\t\7\4\b\t\b\4\t\t\t\4\n\t\n\4\13\t\13\4\f\t\f\4\r\t\r")
        buf.write("\4\16\t\16\4\17\t\17\4\20\t\20\4\21\t\21\4\22\t\22\4\23")
        buf.write("\t\23\4\24\t\24\4\25\t\25\4\26\t\26\4\27\t\27\4\30\t\30")
        buf.write("\4\31\t\31\4\32\t\32\4\33\t\33\4\34\t\34\4\35\t\35\4\36")
        buf.write("\t\36\4\37\t\37\4 \t \4!\t!\4\"\t\"\3\2\3\2\3\2\3\2\3")
        buf.write("\2\3\2\3\2\3\3\3\3\3\3\3\3\3\3\3\3\3\3\3\3\3\4\3\4\3\4")
        buf.write("\3\4\3\4\3\4\3\5\3\5\3\5\3\5\3\6\3\6\3\6\3\6\3\7\3\7\3")
        buf.write("\7\3\7\3\b\3\b\3\b\3\t\3\t\3\t\3\n\3\n\3\n\3\13\3\13\3")
        buf.write("\13\3\13\3\13\3\f\3\f\3\f\3\f\3\f\3\r\3\r\3\16\3\16\3")
        buf.write("\17\3\17\3\20\3\20\3\21\3\21\3\22\3\22\3\23\3\23\3\23")
        buf.write("\3\24\3\24\3\25\3\25\3\26\3\26\3\26\3\27\3\27\3\27\3\30")
        buf.write("\3\30\3\30\3\30\3\31\3\31\3\31\3\32\3\32\3\32\3\32\3\33")
        buf.write("\6\33\u009f\n\33\r\33\16\33\u00a0\3\34\6\34\u00a4\n\34")
        buf.write("\r\34\16\34\u00a5\3\35\3\35\3\35\7\35\u00ab\n\35\f\35")
        buf.write("\16\35\u00ae\13\35\3\35\3\35\3\36\3\36\3\36\7\36\u00b5")
        buf.write("\n\36\f\36\16\36\u00b8\13\36\3\36\3\36\3\37\3\37\3\37")
        buf.write("\5\37\u00bf\n\37\3 \3 \3 \3 \3 \3 \3!\3!\3\"\6\"\u00ca")
        buf.write("\n\"\r\"\16\"\u00cb\3\"\3\"\4\u00ac\u00b6\2#\3\3\5\4\7")
        buf.write("\5\t\6\13\7\r\b\17\t\21\n\23\13\25\f\27\r\31\16\33\17")
        buf.write("\35\20\37\21!\22#\23%\24\'\25)\26+\27-\30/\31\61\32\63")
        buf.write("\33\65\34\67\359\36;\37=\2?\2A\2C \3\2\17\4\2CCcc\4\2")
        buf.write("PPpp\4\2FFff\4\2QQqq\4\2TTtt\4\2VVvv\b\2\60\60\62;B\\")
        buf.write("aac|\u4e02\u9fa7\t\2,,\60\60\62;B\\aac|\u4e02\u9fa7\5")
        buf.write("\2$$,,^^\4\2$$^^\n\2$$\61\61^^ddhhppttvv\5\2\62;CHch\5")
        buf.write("\2\13\f\17\17\"\"\2\u00d3\2\3\3\2\2\2\2\5\3\2\2\2\2\7")
        buf.write("\3\2\2\2\2\t\3\2\2\2\2\13\3\2\2\2\2\r\3\2\2\2\2\17\3\2")
        buf.write("\2\2\2\21\3\2\2\2\2\23\3\2\2\2\2\25\3\2\2\2\2\27\3\2\2")
        buf.write("\2\2\31\3\2\2\2\2\33\3\2\2\2\2\35\3\2\2\2\2\37\3\2\2\2")
        buf.write("\2!\3\2\2\2\2#\3\2\2\2\2%\3\2\2\2\2\'\3\2\2\2\2)\3\2\2")
        buf.write("\2\2+\3\2\2\2\2-\3\2\2\2\2/\3\2\2\2\2\61\3\2\2\2\2\63")
        buf.write("\3\2\2\2\2\65\3\2\2\2\2\67\3\2\2\2\29\3\2\2\2\2;\3\2\2")
        buf.write("\2\2C\3\2\2\2\3E\3\2\2\2\5L\3\2\2\2\7T\3\2\2\2\tZ\3\2")
        buf.write("\2\2\13^\3\2\2\2\rb\3\2\2\2\17f\3\2\2\2\21i\3\2\2\2\23")
        buf.write("l\3\2\2\2\25o\3\2\2\2\27t\3\2\2\2\31y\3\2\2\2\33{\3\2")
        buf.write("\2\2\35}\3\2\2\2\37\177\3\2\2\2!\u0081\3\2\2\2#\u0083")
        buf.write("\3\2\2\2%\u0085\3\2\2\2\'\u0088\3\2\2\2)\u008a\3\2\2\2")
        buf.write("+\u008c\3\2\2\2-\u008f\3\2\2\2/\u0092\3\2\2\2\61\u0096")
        buf.write("\3\2\2\2\63\u0099\3\2\2\2\65\u009e\3\2\2\2\67\u00a3\3")
        buf.write("\2\2\29\u00a7\3\2\2\2;\u00b1\3\2\2\2=\u00bb\3\2\2\2?\u00c0")
        buf.write("\3\2\2\2A\u00c6\3\2\2\2C\u00c9\3\2\2\2EF\7u\2\2FG\7g\2")
        buf.write("\2GH\7c\2\2HI\7t\2\2IJ\7e\2\2JK\7j\2\2K\4\3\2\2\2LM\7")
        buf.write("t\2\2MN\7g\2\2NO\7r\2\2OP\7n\2\2PQ\7c\2\2QR\7e\2\2RS\7")
        buf.write("g\2\2S\6\3\2\2\2TU\7u\2\2UV\7v\2\2VW\7c\2\2WX\7v\2\2X")
        buf.write("Y\7u\2\2Y\b\3\2\2\2Z[\7c\2\2[\\\7x\2\2\\]\7i\2\2]\n\3")
        buf.write("\2\2\2^_\7o\2\2_`\7c\2\2`a\7z\2\2a\f\3\2\2\2bc\7o\2\2")
        buf.write("cd\7k\2\2de\7p\2\2e\16\3\2\2\2fg\7c\2\2gh\7u\2\2h\20\3")
        buf.write("\2\2\2ij\7d\2\2jk\7{\2\2k\22\3\2\2\2lm\7k\2\2mn\7p\2\2")
        buf.write("n\24\3\2\2\2op\7q\2\2pq\7x\2\2qr\7g\2\2rs\7t\2\2s\26\3")
        buf.write("\2\2\2tu\7y\2\2uv\7k\2\2vw\7v\2\2wx\7j\2\2x\30\3\2\2\2")
        buf.write("yz\7~\2\2z\32\3\2\2\2{|\7*\2\2|\34\3\2\2\2}~\7+\2\2~\36")
        buf.write("\3\2\2\2\177\u0080\7$\2\2\u0080 \3\2\2\2\u0081\u0082\7")
        buf.write(".\2\2\u0082\"\3\2\2\2\u0083\u0084\7?\2\2\u0084$\3\2\2")
        buf.write("\2\u0085\u0086\7#\2\2\u0086\u0087\7?\2\2\u0087&\3\2\2")
        buf.write("\2\u0088\u0089\7>\2\2\u0089(\3\2\2\2\u008a\u008b\7@\2")
        buf.write("\2\u008b*\3\2\2\2\u008c\u008d\7>\2\2\u008d\u008e\7?\2")
        buf.write("\2\u008e,\3\2\2\2\u008f\u0090\7@\2\2\u0090\u0091\7?\2")
        buf.write("\2\u0091.\3\2\2\2\u0092\u0093\t\2\2\2\u0093\u0094\t\3")
        buf.write("\2\2\u0094\u0095\t\4\2\2\u0095\60\3\2\2\2\u0096\u0097")
        buf.write("\t\5\2\2\u0097\u0098\t\6\2\2\u0098\62\3\2\2\2\u0099\u009a")
        buf.write("\t\3\2\2\u009a\u009b\t\5\2\2\u009b\u009c\t\7\2\2\u009c")
        buf.write("\64\3\2\2\2\u009d\u009f\t\b\2\2\u009e\u009d\3\2\2\2\u009f")
        buf.write("\u00a0\3\2\2\2\u00a0\u009e\3\2\2\2\u00a0\u00a1\3\2\2\2")
        buf.write("\u00a1\66\3\2\2\2\u00a2\u00a4\t\t\2\2\u00a3\u00a2\3\2")
        buf.write("\2\2\u00a4\u00a5\3\2\2\2\u00a5\u00a3\3\2\2\2\u00a5\u00a6")
        buf.write("\3\2\2\2\u00a68\3\2\2\2\u00a7\u00ac\5\37\20\2\u00a8\u00ab")
        buf.write("\5=\37\2\u00a9\u00ab\n\n\2\2\u00aa\u00a8\3\2\2\2\u00aa")
        buf.write("\u00a9\3\2\2\2\u00ab\u00ae\3\2\2\2\u00ac\u00ad\3\2\2\2")
        buf.write("\u00ac\u00aa\3\2\2\2\u00ad\u00af\3\2\2\2\u00ae\u00ac\3")
        buf.write("\2\2\2\u00af\u00b0\5\37\20\2\u00b0:\3\2\2\2\u00b1\u00b6")
        buf.write("\5\37\20\2\u00b2\u00b5\5=\37\2\u00b3\u00b5\n\13\2\2\u00b4")
        buf.write("\u00b2\3\2\2\2\u00b4\u00b3\3\2\2\2\u00b5\u00b8\3\2\2\2")
        buf.write("\u00b6\u00b7\3\2\2\2\u00b6\u00b4\3\2\2\2\u00b7\u00b9\3")
        buf.write("\2\2\2\u00b8\u00b6\3\2\2\2\u00b9\u00ba\5\37\20\2\u00ba")
        buf.write("<\3\2\2\2\u00bb\u00be\7^\2\2\u00bc\u00bf\t\f\2\2\u00bd")
        buf.write("\u00bf\5? \2\u00be\u00bc\3\2\2\2\u00be\u00bd\3\2\2\2\u00bf")
        buf.write(">\3\2\2\2\u00c0\u00c1\7w\2\2\u00c1\u00c2\5A!\2\u00c2\u00c3")
        buf.write("\5A!\2\u00c3\u00c4\5A!\2\u00c4\u00c5\5A!\2\u00c5@\3\2")
        buf.write("\2\2\u00c6\u00c7\t\r\2\2\u00c7B\3\2\2\2\u00c8\u00ca\t")
        buf.write("\16\2\2\u00c9\u00c8\3\2\2\2\u00ca\u00cb\3\2\2\2\u00cb")
        buf.write("\u00c9\3\2\2\2\u00cb\u00cc\3\2\2\2\u00cc\u00cd\3\2\2\2")
        buf.write("\u00cd\u00ce\b\"\2\2\u00ceD\3\2\2\2\13\2\u00a0\u00a5\u00aa")
        buf.write("\u00ac\u00b4\u00b6\u00be\u00cb\3\b\2\2")
        return buf.getvalue()


class SPLLexer(Lexer):

    atn = ATNDeserializer().deserialize(serializedATN())

    decisionsToDFA = [DFA(ds, i) for i, ds in enumerate(atn.decisionToState)]

    Search = 1
    Replace = 2
    Stats = 3
    Avg = 4
    Max = 5
    Min = 6
    As = 7
    By = 8
    In = 9
    Over = 10
    With = 11
    Vbar = 12
    LParen = 13
    RParen = 14
    DQuotes = 15
    COMMA = 16
    Eq = 17
    Neq = 18
    Lt = 19
    Gt = 20
    Le = 21
    Ge = 22
    And = 23
    Or = 24
    Not = 25
    UnquotedValue = 26
    WcUnquotedValue = 27
    QuotedString = 28
    WcQuotedString = 29
    WS = 30

    channelNames = [u"DEFAULT_TOKEN_CHANNEL", u"HIDDEN"]

    modeNames = ["DEFAULT_MODE"]

    literalNames = ["<INVALID>",
                    "'search'", "'replace'", "'stats'", "'avg'", "'max'", "'min'",
                    "'as'", "'by'", "'in'", "'over'", "'with'", "'|'", "'('", "')'",
                    "'\"'", "','", "'='", "'!='", "'<'", "'>'", "'<='", "'>='"]

    symbolicNames = ["<INVALID>",
                     "Search", "Replace", "Stats", "Avg", "Max", "Min", "As", "By",
                     "In", "Over", "With", "Vbar", "LParen", "RParen", "DQuotes",
                     "COMMA", "Eq", "Neq", "Lt", "Gt", "Le", "Ge", "And", "Or", "Not",
                     "UnquotedValue", "WcUnquotedValue", "QuotedString", "WcQuotedString",
                     "WS"]

    ruleNames = ["Search", "Replace", "Stats", "Avg", "Max", "Min", "As",
                 "By", "In", "Over", "With", "Vbar", "LParen", "RParen",
                 "DQuotes", "COMMA", "Eq", "Neq", "Lt", "Gt", "Le", "Ge",
                 "And", "Or", "Not", "UnquotedValue", "WcUnquotedValue",
                 "QuotedString", "WcQuotedString", "ESC", "UNICODE", "HEX",
                 "WS"]

    grammarFileName = "SPL.g4"

    def __init__(self, input=None, output: TextIO = sys.stdout):
        super().__init__(input, output)
        self.checkVersion("4.8")
        self._interp = LexerATNSimulator(
            self, self.atn, self.decisionsToDFA, PredictionContextCache())
        self._actions = None
        self._predicates = None
